# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-11 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', embed_video.fields.EmbedVideoField(verbose_name='Endereço do SoundCloud')),
                ('title', models.CharField(blank=True, max_length=1200, verbose_name='Título do áudio')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio', to='school.Classroom')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.ImageField(default='pic_folder/user/no-img.jpg', upload_to='media', verbose_name='Endereço da imagem')),
                ('alt', models.CharField(blank=True, max_length=1200, verbose_name='Texto alternativo')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image', to='school.Classroom')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True)),
                ('name', models.CharField(blank=True, max_length=600, verbose_name='Nome')),
                ('access_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data de acesso')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='link', to='school.Classroom')),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('text', models.TextField(blank=True, verbose_name='Texto')),
                ('source', models.URLField(blank=True, verbose_name='Link para a fonte')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='text', to='school.Classroom')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', embed_video.fields.EmbedVideoField(verbose_name='Endereço do Youtube')),
                ('title', models.CharField(blank=True, max_length=1200, verbose_name='Título do vídeo')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video', to='school.Classroom')),
            ],
        ),
    ]
