# Generated by Django 2.1.7 on 2019-03-13 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_auto_20190220_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='access_date',
            field=models.DateField(verbose_name='Data de acesso'),
        ),
    ]
