# Generated by Django 2.1.7 on 2019-02-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='year',
            field=models.CharField(blank=True, help_text='Série ou ano. Ex: 1º ano', max_length=20),
        ),
    ]
